language: php

sudo: false

php:
    - '7.0'

before_install:
    - composer self-update

install:
    - composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction

before_script:
    - phpenv config-rm xdebug.ini

script:
    - make tests
